# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=40)),
                ('s_sno', models.IntegerField()),
                ('s_sex', models.CharField(max_length=20)),
                ('s_score', models.IntegerField()),
            ],
        ),
    ]
