# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-01 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('passworld', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('money', models.CharField(max_length=100)),
                ('E_mail', models.CharField(max_length=100)),
            ],
        ),
    ]
